# palavras.py
# ATENÇÃO: A estrutura deste ficheiro mudou.
# Agora usamos um dicionário principal chamado PALAVRAS_POR_CATEGORIA.
# Este arquivo contém 5 categorias com 50 palavras cada, totalizando 250 palavras.

PALAVRAS_POR_CATEGORIA = {
    "Frutas": {
        "morango": ["É vermelha, pequena e tem pintinhas pretas.", "Combina perfeitamente com chocolate e chantilly."],
        "abacaxi": ["Tem uma coroa e sua casca é espinhosa.", "É o símbolo de um famoso país tropical."],
        "melancia": ["Verde por fora, vermelha por dentro e cheia de sementes.", "É muito consumida no verão por ser refrescante."],
        "banana": ["É amarela, alongada e rica em potássio.", "É a fruta preferida dos Minions."],
        "laranja": ["Dá nome a uma cor e é rica em Vitamina C.", "Seu suco é muito popular no café da manhã."],
        "manga": ["Fruta tropical de polpa suculenta e amarela.", "Existe a 'espada', a 'rosa' e a 'palmer'."],
        "uva": ["Pode ser verde ou roxa, nasce em cachos.", "É a matéria-prima para a fabricação do vinho."],
        "pera": ["Tem formato de 'sino' e casca geralmente verde ou amarelada.", "Seu nome é igual ao de um sinal de trânsito."],
        "kiwi": ["Tem casca marrom e 'peluda', mas por dentro é verde.", "Seu nome é o mesmo de uma ave da Nova Zelândia."],
        "cereja": ["Pequena, vermelha e geralmente vem em pares.", "É a 'coroa' de muitos bolos e sobremesas."],
        "maca": ["Pode ser vermelha ou verde.", "Dizem que uma por dia mantém o médico longe."],
        "limao": ["É azedo e usado para fazer caipirinha.", "Geralmente é verde ou amarelo."],
        "maracuja": ["Sua polpa é cheia de sementes e é conhecido por ser um calmante natural.", "Seu suco também é chamado de 'suco da paixão'."],
        "goiaba": ["Pode ser branca ou vermelha por dentro.", "É comum comê-la com queijo."],
        "caju": ["Seu fruto verdadeiro é a castanha.", "Seu suco é muito popular no Nordeste brasileiro."],
        "abacate": ["É verde, cremoso e usado para fazer guacamole.", "Rico em gorduras boas."],
        "acai": ["Fruto roxo da Amazônia, consumido em tigelas.", "Frequentemente acompanhado por granola e banana."],
        "coco": ["Tem uma casca dura e água refrescante por dentro.", "Sua polpa branca é usada em muitas receitas de doces."],
        "caqui": ["Fruta de cor alaranjada e textura macia.", "Quando não está maduro, 'amarra' a boca."],
        "figo": ["Pode ser roxo ou verde, muito doce.", "Frequentemente consumido em compotas ou cristalizado."],
        "amora": ["Pequena fruta silvestre de cor escura.", "Nasce em arbustos espinhosos."],
        "framboesa": ["Parente da amora, mas de cor vermelha.", "Tem um sabor levemente ácido."],
        "jabuticaba": ["Frutinha preta que nasce direto no tronco da árvore.", "Típica do Brasil."],
        "lichia": ["Tem casca vermelha e rugosa, com polpa branca e translúcida.", "Fruta de origem asiática."],
        "melao": ["Parente da melancia, mas com polpa alaranjada ou esverdeada.", "Tem um aroma muito característico."],
        "pessego": ["Tem uma casca aveludada.", "Sua versão em calda é muito comum em sobremesas."],
        "pitanga": ["Pequena, vermelha e com 'gomos'.", "Fruta muito comum em quintais brasileiros."],
        "pitaya": ["Conhecida como fruta-do-dragão.", "Sua aparência é exótica, rosa por fora com 'escamas' verdes."],
        "roma": ["Cheia de sementes vermelhas e suculentas por dentro.", "Símbolo de sorte e prosperidade."],
        "tangerina": ["Também conhecida como mexerica ou bergamota.", "É fácil de descascar."],
        "carambola": ["Quando cortada, seus pedaços têm formato de estrela.", "Tem um sabor agridoce."],
        "cupuacu": ["Fruta amazônica de casca dura e polpa branca e ácida.", "Muito usada em cremes, sucos e sorvetes."],
        "damasco": ["Pequeno e alaranjado, parece um mini-pêssego.", "Muito consumido em sua forma seca."],
        "graviola": ["Casca verde com 'espinhos' macios, polpa branca.", "Seu sorvete é muito popular."],
        "jaca": ["Fruta enorme e pesada, com gomos doces.", "Ou você ama, ou você odeia."],
        "nespera": ["Também conhecida como ameixa-amarela.", "Pequena, alaranjada e com grandes sementes."],
        "pequi": ["Fruto do cerrado, amarelo e com um cheiro forte.", "Cuidado com os espinhos ao roer."],
        "seriguela": ["Pequena, de cor vermelha ou amarela quando madura.", "Muito comum no Nordeste na época do Natal."],
        "tamarindo": ["Fruto em vagem, com polpa ácida e marrom.", "Usado para fazer sucos e doces."],
        "guarana": ["Fruto da Amazônia que parece um olho humano.", "Famoso por ser usado em refrigerantes e energéticos."],
        "nectarina": ["É uma variação do pêssego, mas com a casca lisa.", "Seu nome vem de 'néctar'."],
        "jambo": ["Fruta de casca rosa ou roxa, formato de sino.", "Tem uma polpa branca e levemente adocicada."],
        "atemoya": ["Cruzamento da cherimóia com a fruta-do-conde.", "Polpa doce e sem sementes."],
        "cambuci": ["Fruto verde com formato de 'disco voador'.", "É azedo e usado em sucos e cachaças."],
        "bacuri": ["Fruta amazônica com polpa branca e cremosa.", "Muito usada na culinária do Pará e Maranhão."],
        "cagaita": ["Fruto do cerrado, pequeno e amarelado.", "Tem efeito laxativo se consumido em excesso."],
        "sapoti": ["Casca marrom, polpa doce que lembra caramelo.", "Fruta de origem da América Central."],
        "umbu": ["Fruto do sertão nordestino, pequeno e esverdeado.", "Seu nome vem do tupi e significa 'árvore que dá de beber'."],
        "jenipapo": ["Usado para fazer licor e doces.", "Sua polpa escurece em contato com o ar."],
        "mirtilo": ["Pequena fruta azulada, também conhecida como blueberry.", "Considerado um superalimento."]
    },
    "Países": {
        "brasil": ["País do futebol, samba e carnaval.", "Sua capital é Brasília."],
        "portugal": ["Nosso colonizador, fica na Europa.", "Sua capital é Lisboa."],
        "japao": ["Conhecido como a 'Terra do Sol Nascente'.", "Famoso por sushis, samurais e animes."],
        "egito": ["Famoso por suas pirâmides e pelo Rio Nilo.", "Sua escrita antiga eram os hieróglifos."],
        "italia": ["País em formato de bota, famoso por massas e pizzas.", "O Coliseu e a Torre de Pisa ficam lá."],
        "argentina": ["Nosso vizinho, famoso pelo tango e pelo futebol.", "Sua capital é Buenos Aires."],
        "china": ["O país mais populoso do mundo.", "Conhecido pela sua Grande Muralha."],
        "australia": ["Famoso por cangurus e coalas.", "É tanto um país quanto um continente."],
        "canada": ["País da América do Norte conhecido pela folha de bordo em sua bandeira.", "Suas línguas oficiais são o inglês e o francês."],
        "russia": ["O maior país do mundo em área.", "Famoso pelo frio, pela vodka e pela Praça Vermelha."],
        "espanha": ["Famoso pelas touradas e pela paella.", "Terra de Picasso e Gaudí."],
        "franca": ["País da Torre Eiffel, do Louvre e dos vinhos.", "Sua capital é Paris."],
        "alemanha": ["Conhecido pela cerveja, salsichas e carros de luxo.", "O Muro de Berlim dividiu sua capital por décadas."],
        "reino unido": ["Formado por Inglaterra, Escócia, Gales e Irlanda do Norte.", "A família real é uma de suas instituições mais famosas."],
        "estados unidos": ["País do Tio Sam, da Estátua da Liberdade e de Hollywood.", "Sua capital é Washington D.C."],
        "mexico": ["Famoso pelos sombreros, mariachis e pela culinária apimentada.", "Terra das antigas civilizações Asteca e Maia."],
        "india": ["Segundo país mais populoso, famoso por Bollywood e pelo Taj Mahal.", "O hinduísmo é sua principal religião."],
        "africa do sul": ["País de Nelson Mandela e do Apartheid.", "Possui três capitais."],
        "grecia": ["Berço da democracia, da filosofia e dos Jogos Olímpicos.", "Famoso por suas ilhas e ruínas antigas."],
        "suecia": ["País escandinavo famoso por uma loja de móveis e pelo grupo ABBA.", "Sua capital é Estocolmo."],
        "noruega": ["País dos vikings e dos fiordes.", "Famoso pelo fenômeno da Aurora Boreal."],
        "suica": ["Famosa por chocolates, relógios e bancos.", "É um país neutro e não se envolve em guerras."],
        "holanda": ["Conhecida por seus moinhos de vento, tulipas e canais.", "Também é chamada de Países Baixos."],
        "irlanda": ["A 'Ilha Esmeralda', famosa pelos trevos e leprechauns.", "O dia de São Patrício é sua maior festa nacional."],
        "turquia": ["País que se localiza em dois continentes: Europa e Ásia.", "Istambul é sua cidade mais famosa."],
        "coreia do sul": ["Potência tecnológica, terra do K-Pop e de grandes empresas de eletrônicos.", "Sua capital é Seul."],
        "tailandia": ["País do sudeste asiático famoso por suas praias paradisíacas e templos budistas.", "Sua capital é Bangkok."],
        "chile": ["País longo e estreito, famoso por seus vinhos e pelo Deserto do Atacama.", "A Ilha de Páscoa pertence a este país."],
        "colombia": ["Famosa pelo seu café e por suas esmeraldas.", "Terra do escritor Gabriel García Márquez."],
        "peru": ["País dos Incas e de Machu Picchu.", "A lhama é um de seus animais símbolo."],
        "cuba": ["Ilha caribenha famosa por seus charutos e carros antigos.", "País com regime socialista."],
        "jamaica": ["Terra do reggae e de Bob Marley.", "Usain Bolt, o homem mais rápido do mundo, nasceu lá."],
        "marrocos": ["País do norte da África, famoso por seus desertos e mercados coloridos.", "Cidades famosas incluem Marrakech e Casablanca."],
        "quenia": ["País africano famoso pelos safáris e pela grande migração de gnus.", "Grandes maratonistas vêm deste país."],
        "vietna": ["País do sudeste asiático que foi palco de uma famosa guerra.", "Sua culinária é conhecida pelo 'pho'."],
        "israel": ["Considerado a 'Terra Santa' por várias religiões.", "O Mar Morto fica em seu território."],
        "ira": ["Antigamente conhecido como Pérsia.", "Famoso por seus tapetes."],
        "arabia saudita": ["Maior produtor de petróleo do mundo.", "Meca, a cidade sagrada do Islamismo, fica aqui."],
        "nova zelandia": ["País da Oceania, famoso pelos esportes radicais e pela cultura Maori.", "Cenário dos filmes 'O Senhor dos Anéis'."],
        "finlandia": ["Conhecido como a 'Terra dos Mil Lagos'.", "Dizem que é a casa oficial do Papai Noel."],
        "polonia": ["País de nascimento do Papa João Paulo II e de Marie Curie.", "Auschwitz, o campo de concentração, fica em seu território."],
        "islandia": ["'Terra do Gelo e do Fogo', com vulcões e geleiras.", "Sua capital é Reykjavik."],
        "belgica": ["Famoso por seus waffles, batatas fritas e chocolates.", "Bruxelas, sua capital, é sede da União Europeia."],
        "dinamarca": ["País de Hans Christian Andersen, autor de 'A Pequena Sereia'.", "Famoso pelos blocos de montar LEGO."],
        "ucrania": ["País do leste europeu, celeiro da Europa.", "O desastre nuclear de Chernobyl ocorreu aqui."],
        "hungria": ["Sua capital, Budapeste, é dividida pelo rio Danúbio.", "Famoso pelo cubo mágico e pela páprica."],
        "uruguai": ["Pequeno vizinho do Brasil, primeiro país a sediar uma Copa do Mundo.", "Famoso pelo mate e pelo doce de leite."],
        "venezuela": ["Possui as maiores reservas de petróleo do mundo.", "O Salto Ángel, a cachoeira mais alta do mundo, fica aqui."],
        "nigeria": ["O país mais populoso da África.", "Potência na indústria cinematográfica, conhecida como 'Nollywood'."],
        "indonesia": ["O maior arquipélago do mundo, com milhares de ilhas.", "A ilha de Bali é um famoso destino turístico."]
    },
    "Cidades": {
        "salvador": ["Primeira capital do Brasil.", "Conhecida pelo Pelourinho e pelo carnaval de rua."],
        "recife": ["Capital de Pernambuco, conhecida como a 'Veneza Brasileira'.", "Famosa pela praia de Boa Viagem e pelos tubarões."],
        "manaus": ["Principal cidade da Amazônia.", "O Encontro das Águas dos rios Negro e Solimões acontece lá."],
        "curitiba": ["Capital do Paraná, conhecida por seu sistema de transporte e parques.", "O Jardim Botânico é seu principal cartão-postal."],
        "fortaleza": ["Capital do Ceará, famosa por suas praias e pelo humor.", "O Beach Park, um famoso parque aquático, fica perto."],
        "belo horizonte": ["Capital de Minas Gerais, cercada por serras.", "Conhecida pelo pão de queijo e pelo complexo da Pampulha."],
        "sao paulo": ["A maior cidade do Brasil, nunca dorme.", "Conhecida como a 'terra da garoa'."],
        "rio de janeiro": ["Famoso pelo Cristo Redentor e pelo Pão de Açúcar.", "Conhecida como a 'Cidade Maravilhosa'."],
        "paris": ["Capital da França, conhecida como a 'Cidade Luz'.", "A Torre Eiffel é seu monumento mais famoso."],
        "nova york": ["Cidade que nunca dorme, nos EUA.", "A Estátua da Liberdade e a Times Square ficam lá."],
        "brasilia": ["Capital do Brasil, planejada por Oscar Niemeyer e Lúcio Costa.", "Tem formato de avião."],
        "florianopolis": ["Capital de Santa Catarina, conhecida como 'Ilha da Magia'.", "Famosa por suas praias e pela Ponte Hercílio Luz."],
        "porto alegre": ["Capital do Rio Grande do Sul.", "Famosa pelo pôr do sol no rio Guaíba e pelo churrasco."],
        "goiania": ["Capital de Goiás, planejada e conhecida por ser muito arborizada.", "Palco de um grave acidente com Césio-137."],
        "belem": ["Capital do Pará, porta de entrada para a Amazônia.", "Famosa pelo mercado Ver-o-Peso e pelo Círio de Nazaré."],
        "sao luis": ["Capital do Maranhão, conhecida como a 'Ilha do Amor'.", "Seu centro histórico tem azulejos portugueses e é Patrimônio da Humanidade."],
        "natal": ["Capital do Rio Grande do Norte, conhecida como a 'Cidade do Sol'.", "Famosa por suas dunas e passeios de buggy."],
        "joao pessoa": ["Capital da Paraíba, onde o sol nasce primeiro nas Américas.", "Conhecida pela Ponta do Seixas."],
        "teresina": ["Única capital do Nordeste que não fica no litoral.", "É a capital do Piauí."],
        "maceio": ["Capital de Alagoas, conhecida como o 'Caribe Brasileiro'.", "Famosa por suas piscinas naturais e praias de águas claras."],
        "aracaju": ["Capital de Sergipe, cidade planejada.", "A Orla de Atalaia é um de seus principais pontos turísticos."],
        "campo grande": ["Capital do Mato Grosso do Sul, conhecida como 'Cidade Morena'.", "Porta de entrada para o Pantanal e Bonito."],
        "cuiaba": ["Capital de Mato Grosso, localizada no centro geodésico da América do Sul.", "Faz muito calor e é porta de entrada para o Pantanal e a Chapada dos Guimarães."],
        "porto velho": ["Capital de Rondônia.", "Marcada pela construção da Estrada de Ferro Madeira-Mamoré."],
        "boa vista": ["Capital de Roraima, única capital brasileira totalmente no Hemisfério Norte.", "Planejada em formato de leque."],
        "macapa": ["Capital do Amapá, cortada pela linha do Equador.", "O Marco Zero é seu ponto turístico mais famoso."],
        "rio branco": ["Capital do Acre.", "Seu nome é uma homenagem a um famoso diplomata brasileiro."],
        "palmas": ["A mais nova capital do Brasil, em Tocantins.", "Cidade planejada com avenidas largas."],
        "vitoria": ["Capital do Espírito Santo, localizada em uma ilha.", "Famosa pela moqueca capixaba."],
        "londres": ["Capital da Inglaterra, famosa pelo Big Ben, ônibus de dois andares e cabines telefônicas vermelhas.", "O rio Tâmisa corta a cidade."],
        "roma": ["Capital da Itália, conhecida como a 'Cidade Eterna'.", "O Coliseu e o Vaticano estão lá."],
        "toquio": ["Capital do Japão, uma das cidades mais populosas do mundo.", "Mistura de tradição e tecnologia de ponta."],
        "moscou": ["Capital da Rússia, famosa pela Praça Vermelha e pelo Kremlin.", "Suas estações de metrô são consideradas obras de arte."],
        "pequim": ["Capital da China, com uma história milenar.", "A Cidade Proibida fica no coração da cidade."],
        "sydney": ["A cidade mais populosa da Austrália.", "Famosa pela sua Opera House e pela Harbour Bridge."],
        "cairo": ["Capital do Egito, localizada às margens do rio Nilo.", "As Pirâmides de Gizé ficam em sua região metropolitana."],
        "buenos aires": ["Capital da Argentina, conhecida pelo tango e pela Casa Rosada.", "Bairros famosos incluem La Boca e Palermo."],
        "lisboa": ["Capital de Portugal, famosa por seus bondes amarelos e pelo fado.", "A Torre de Belém e o Mosteiro dos Jerónimos são pontos turísticos."],
        "madrid": ["Capital da Espanha, famosa por seus museus (Prado, Reina Sofia) e pela vida noturna.", "O Palácio Real é a residência oficial do rei."],
        "amsterda": ["Capital da Holanda, famosa por seus canais, bicicletas e casas inclinadas.", "A Casa de Anne Frank é um de seus museus mais visitados."],
        "berlim": ["Capital da Alemanha.", "O Portão de Brandemburgo é seu maior símbolo."],
        "istambul": ["A maior cidade da Turquia, localizada entre a Europa e a Ásia.", "Antigamente chamada de Constantinopla."],
        "atenas": ["Capital da Grécia, berço da civilização ocidental.", "A Acrópole domina a paisagem da cidade."],
        "dublin": ["Capital da Irlanda, famosa por seus pubs e pela cerveja Guinness.", "O Temple Bar é sua área mais boêmia."],
        "toronto": ["A maior cidade do Canadá.", "A CN Tower é seu marco mais famoso."],
        "los angeles": ["Cidade da Califórnia, centro da indústria do cinema.", "A Calçada da Fama e o letreiro de Hollywood ficam aqui."],
        "cidade do mexico": ["A capital do México, uma das maiores cidades do mundo.", "Construída sobre as ruínas da antiga capital asteca, Tenochtitlán."],
        "santiago": ["Capital do Chile, cercada pela Cordilheira dos Andes.", "É uma das cidades com melhor qualidade de vida da América do Sul."],
        "lima": ["Capital do Peru, conhecida como a capital gastronômica da América Latina.", "Seu centro histórico é Patrimônio da Humanidade."],
        "bangkok": ["Capital da Tailândia, conhecida por seus templos e mercados flutuantes.", "O trânsito é caótico."]
    },
    "Animais": {
        "elefante": ["Tem tromba, grandes orelhas e é conhecido pela memória.", "É o maior mamífero terrestre."],
        "girafa": ["Famosa pelo seu pescoço muito comprido.", "É o animal mais alto do mundo."],
        "leao": ["Considerado o 'Rei da Selva'.", "O macho tem uma juba característica."],
        "macaco": ["Gosta de bananas e de pular em árvores.", "Animal inteligente e social, vive em bandos."],
        "tubarao": ["Grande predador dos mares.", "Aparece em filmes famosos como uma grande ameaça."],
        "pinguim": ["Ave que não voa e vive em climas frios.", "Veste um 'smoking' natural preto e branco."],
        "jacare": ["Réptil que vive em rios e pântanos.", "Parente próximo do crocodilo."],
        "arara": ["Ave colorida, símbolo da fauna brasileira.", "Sua plumagem pode ser azul, amarela e vermelha."],
        "onca": ["O maior felino das Américas.", "Sua pele é amarelada com manchas pretas."],
        "cavalo": ["Usado como meio de transporte e em esportes.", "Relincha e vive em estábulos."],
        "cachorro": ["Conhecido como o melhor amigo do homem.", "Late e abana o rabo."],
        "gato": ["Animal doméstico independente e que mia.", "Dizem que tem sete ou nove vidas."],
        "lobo": ["Parente selvagem do cachorro, uiva para a lua.", "Vive em alcateias."],
        "tigre": ["O maior felino do mundo, com listras pretas.", "Vive nas florestas da Ásia."],
        "urso": ["Mamífero grande que pode hibernar no inverno.", "O 'Pooh' é um famoso personagem desta espécie."],
        "zebra": ["Animal africano que parece um cavalo de pijama.", "Suas listras são como uma impressão digital."],
        "hipopotamo": ["Grande mamífero africano que passa a maior parte do tempo na água.", "Apesar da aparência dócil, é muito perigoso."],
        "rinoceronte": ["Possui um ou dois chifres no nariz.", "Sua pele é grossa e parece uma armadura."],
        "baleia": ["O maior animal do planeta, vive no oceano.", "A 'azul' é a maior espécie."],
        "golfinho": ["Mamífero aquático muito inteligente e brincalhão.", "Comunica-se por meio de assobios e cliques."],
        "aguia": ["Ave de rapina com visão aguçada.", "É símbolo de força e liberdade em muitas culturas."],
        "coruja": ["Ave noturna que consegue girar a cabeça quase 360 graus.", "Símbolo da sabedoria."],
        "tucano": ["Ave tropical famosa pelo seu bico enorme e colorido.", "Apesar do tamanho, seu bico é leve."],
        "cobra": ["Réptil sem patas que rasteja.", "Algumas espécies são peçonhentas."],
        "tartaruga": ["Réptil que carrega sua casa nas costas.", "Pode ser marinha ou terrestre."],
        "sapo": ["Anfíbio que vive perto da água e coaxa.", "Não é um príncipe disfarçado."],
        "morcego": ["O único mamífero que pode voar.", "Dorme de cabeça para baixo."],
        "esquilo": ["Pequeno roedor que adora nozes e vive em árvores.", "Conhecido por ter uma cauda peluda."],
        "abelha": ["Inseto que produz mel e vive em colmeias.", "Sua picada pode ser dolorosa."],
        "formiga": ["Inseto que vive em colônias e é conhecido por ser trabalhador.", "Consegue carregar muitas vezes o seu próprio peso."],
        "borboleta": ["Inseto com asas coloridas que antes era uma lagarta.", "Passa por um processo de metamorfose."],
        "raposa": ["Animal astuto e oportunista, parente dos cães.", "Famosa em muitas fábulas."],
        "coelho": ["Parente da lebre, famoso pelas orelhas compridas.", "É o símbolo da Páscoa."],
        "porco": ["Animal de fazenda que fornece carne como bacon e linguiça.", "Gosta de rolar na lama."],
        "vaca": ["Animal de fazenda que nos dá leite.", "Muge e tem chifres."],
        "galinha": ["Ave de fazenda que bota ovos.", "O macho é o galo, que canta de manhã."],
        "pato": ["Ave aquática que faz 'quack'.", "Tem membranas nas patas que ajudam a nadar."],
        "ovelha": ["Animal de fazenda que nos fornece lã.", "Bala e vive em rebanhos."],
        "camelo": ["Animal do deserto com uma ou duas corcovas.", "Armazena gordura, e não água, nas corcovas."],
        "polvo": ["Molusco com oito tentáculos.", "Consegue soltar tinta para se defender."],
        "estrela do mar": ["Animal marinho com cinco ou mais braços.", "Não tem cérebro nem sangue."],
        "pavao": ["Ave conhecida pela cauda exuberante e colorida do macho.", "Exibe sua cauda para atrair a fêmea."],
        "cisne": ["Ave aquática elegante, branca ou preta.", "O 'patinho feio' da história virou um destes."],
        "flamengo": ["Ave pernalta de cor rosa.", "Sua cor vem dos pigmentos dos crustáceos que come."],
        "preguica": ["O mamífero mais lento do mundo.", "Vive em árvores e dorme a maior parte do dia."],
        "capivara": ["O maior roedor do mundo, muito social.", "É comum vê-la em parques urbanos perto de lagos."],
        "tamandua": ["Não tem dentes e usa sua longa língua para comer formigas e cupins.", "Sua cauda parece uma bandeira."],
        "beija flor": ["Pequena ave que bate as asas muito rápido.", "Alimenta-se do néctar das flores."],
        "hamster": ["Pequeno roedor de estimação que gosta de rodas de exercício.", "Guarda comida em suas bochechas."]
    },
    "Objetos": {
        "computador": ["Máquina que processa informações.", "Essencial para o trabalho e diversão hoje em dia."],
        "cadeira": ["Serve para uma pessoa se sentar.", "Pode ter de uma a quatro pernas."],
        "oculos": ["Acessório usado no rosto para enxergar melhor ou se proteger do sol.", "Possui duas lentes."],
        "telefone": ["Usado para se comunicar a distância.", "Sua versão moderna é chamada de 'smartphone'."],
        "livro": ["Contém histórias, informações ou conhecimento.", "É feito de papel e pode ter capa dura ou mole."],
        "garfo": ["Utensílio de cozinha usado para espetar alimentos.", "Geralmente usado junto com a faca."],
        "chave": ["Usada para abrir e fechar portas.", "Cada uma tem um segredo único."],
        "relogio": ["Mostra as horas.", "Pode ser de pulso, de parede ou digital."],
        "guarda chuva": ["Usado para se proteger da chuva.", "Abre e fecha, formando uma cúpula."],
        "escova": ["Pode ser de dentes ou de cabelo.", "Serve para limpar ou pentear."],
        "mesa": ["Móvel onde fazemos refeições ou trabalhamos.", "Pode ser de madeira, vidro ou metal."],
        "cama": ["Móvel onde dormimos.", "Pode ser de solteiro ou de casal."],
        "sofa": ["Móvel para sentar na sala de estar.", "Geralmente fica em frente à televisão."],
        "televisao": ["Aparelho que exibe imagens e sons.", "O controle remoto é seu melhor amigo."],
        "geladeira": ["Eletrodoméstico que mantém os alimentos frios.", "Também chamada de refrigerador."],
        "fogao": ["Eletrodoméstico usado para cozinhar.", "Pode ter boca a gás ou por indução."],
        "caneta": ["Usada para escrever com tinta.", "Pode ser esferográfica, de gel ou tinteiro."],
        "lapis": ["Usado para escrever ou desenhar, pode ser apagado.", "Feito de madeira e grafite."],
        "tesoura": ["Instrumento com duas lâminas usado para cortar.", "Crianças devem usar a versão sem ponta."],
        "prato": ["Onde colocamos a comida para comer.", "Pode ser fundo ou raso."],
        "copo": ["Recipiente para beber líquidos.", "Geralmente feito de vidro."],
        "panela": ["Recipiente usado para cozinhar no fogão.", "A de pressão cozinha mais rápido."],
        "mochila": ["Bolsa usada nas costas para carregar objetos.", "Muito usada por estudantes."],
        "sapato": ["Calçado que protege os pés.", "Existe o social, o tênis, a bota, etc."],
        "lampada": ["Objeto que ilumina o ambiente.", "A invenção é atribuída a Thomas Edison."],
        "espelho": ["Superfície que reflete a imagem.", "Narciso se apaixonou pelo seu próprio reflexo em um."],
        "travesseiro": ["Usado para apoiar a cabeça ao dormir.", "Pode ser de penas, espuma ou látex."],
        "martelo": ["Ferramenta usada para bater em pregos.", "O Thor usa um como arma."],
        "parafuso": ["Peça metálica usada para unir objetos.", "Precisa de uma chave de fenda ou Philips para ser apertado."],
        "serrote": ["Ferramenta com lâmina dentada usada para cortar madeira.", "Faz um barulho característico."],
        "escada": ["Objeto usado para alcançar lugares altos.", "Pode ser de mão ou fixa."],
        "vassoura": ["Usada para varrer o chão.", "Meio de transporte preferido das bruxas."],
        "balde": ["Recipiente para carregar água ou outros materiais.", "Usado para limpeza ou em construções."],
        "bola": ["Objeto esférico usado em muitos esportes.", "A de futebol é a mais famosa no Brasil."],
        "dado": ["Cubo com números de um a seis em suas faces.", "Usado em jogos de tabuleiro para sorteio."],
        "anel": ["Joia usada no dedo.", "Pode simbolizar um noivado ou casamento."],
        "colar": ["Adorno usado ao redor do pescoço.", "Pode ter um pingente."],
        "pulseira": ["Acessório usado no pulso.", "Pode ser de metal, couro ou tecido."],
        "brinco": ["Joia usada na orelha.", "Geralmente vendido em pares."],
        "chapeu": ["Acessório usado na cabeça para proteger do sol ou por estilo.", "O de palha é comum em festas juninas."],
        "cinto": ["Usado para segurar as calças na cintura.", "Pode ter uma fivela decorativa."],
        "carteira": ["Onde guardamos dinheiro, cartões e documentos.", "Geralmente levada no bolso ou na bolsa."],
        "moeda": ["Dinheiro em formato de metal.", "Cara ou coroa?"],
        "selo": ["Pequeno papel colado em cartas para o envio.", "Item de colecionador."],
        "apito": ["Instrumento que produz um som agudo quando soprado.", "Usado por juízes e guardas de trânsito."],
        "violao": ["Instrumento musical de cordas, popular na MPB.", "Pode ser acústico ou elétrico."],
        "piano": ["Instrumento musical de teclas pretas e brancas.", "É um instrumento de percussão e de cordas."],
        "bateria": ["Conjunto de tambores e pratos.", "Marca o ritmo da música."],
        "microfone": ["Amplifica a voz.", "Essencial para cantores e palestrantes."],
        "camera": ["Usada para tirar fotos ou gravar vídeos.", "Diga 'xis'!"]
    }
}

